from app.api.v1 import (
    auth_router,
    users_router,
    upload_router,
    shop_router,
    admin_router,
    orders_router,
    rider_router,
    review_router,
    wallet_router,
    earnings_router,
    config_router,
    favorites_router,
    coupons_router,
    audit_router,
    payment_router,
)

__all__ = [
    "auth_router",
    "users_router",
    "upload_router",
    "shop_router",
    "admin_router",
    "orders_router",
    "rider_router",
    "review_router",
    "wallet_router",
    "earnings_router",
    "config_router",
    "favorites_router",
    "coupons_router",
    "audit_router",
    "payment_router",
]
